global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: data-lineage
    static_configs:
      - targets: ["data-lineage:8000"]
        labels: { service: data-lineage }

  - job_name: lineage-pg
    static_configs:
      - targets: ["postgres-exporter-lineage:9187"]
        labels: { service: data-lineage, db: lineage-pg }

  - job_name: marquez
    static_configs:
      - targets: ["marquez:5001"]
        labels: { service: marquez }

  - job_name: marquez-pg
    static_configs:
      - targets: ["postgres-exporter-marquez:9187"]
        labels: { service: marquez, db: marquez-pg }
